In [174]:
import tensorflow.compat.v1 as tf


# Session in TensorFlow 
A session allows to execute graphs or part of graphs. It allocates resources (on one or more machines) 
for that and holds the actual values of intermediate results and variables.

In [135]:
tf.disable_eager_execution() # for used tf correctly 
sess=tf.Session()
#print(sess.run())


# Constant in TensorFlow
when you declare some constant, its value can't be changed in the future (also the initialization should be with a value, not with operation).

In [136]:
b=tf.constant(5)
print(sess.run(b))
print(b)
#------------------------
name=tf.constant('mahmoud khaled')
print(sess.run(name))
#------------------------
a=tf.constant(9,tf.float32)
print(sess.run(a))
#------------------------
mat=tf.constant([1,2,892,5])
print(sess.run(mat))
#-----------------------

5
Tensor("Const_40:0", shape=(), dtype=int32)
b'mahmoud khaled'
9.0
[  1   2 892   5]


# Variables in TensorFlow
when you declare a Variable, you can change its value in the future with tf.assign() method (and the initialization can be achieved with a value or operation).

In [137]:
price = tf.Variable(20) 
sess.run(tf.global_variables_initializer()) # use after declare  variable to work corectly.
print('original price is : ',sess.run(price))
# we can change variable with two way 
#first one we can declare variable with same name 
price = tf.Variable(123) 
sess.run(tf.global_variables_initializer()) # use after declare  variable to work corectly.
print('after change price is : ',sess.run(price))    
#second one with assign method 
newprice=tf.assign(price,999)
sess.run(tf.global_variables_initializer()) # use after declare every variable to work corectly.
print('after change2 price is : ',sess.run(newprice))    

original price is :  20
after change price is :  123
after change2 price is :  999


In [143]:
ii=tf.Variable(0)
sess.run(tf.global_variables_initializer())
for i in range(10):
    ii=tf.assign(ii,ii+1)
    sess.run(tf.global_variables_initializer())
    print("i = ",i)
    



i =  0
i =  1
i =  2
i =  3
i =  4
i =  5
i =  6
i =  7
i =  8
i =  9


# Placeholder in TensorFlow
. A placeholder is simply a variable that we will assign data to at a later date. It allows us to create our operations and build our computation graph, without needing the data


In [145]:
x = tf.placeholder(tf.float32)
y = x * 2
with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[2. 4. 6.]


In [146]:

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = tf.constant(8,tf.float32)
w = tf.constant(6,tf.float32)

b = x*2 + 3*y**4 - 4/z + w-9

with tf.Session() as sess :
    result = sess.run(b , feed_dict ={x:3.0,y:4.0})
    print(result)

770.5


In [148]:
w = tf.constant([5.0])
b = tf.Variable([7.0],tf.float32)

x = tf.placeholder(tf.float32)

LinearRegressionModel = w*x + b

with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    print(sess.run(LinearRegressionModel,{x:[3,5,7,9]}))

[22. 32. 42. 52.]


# Operation in TensorFlow

In [163]:
s1=tf.constant('Hi ')
s2=tf.constant('Mahmoud')
s3=tf.add(s1,s2)
sess=tf.Session()
print(sess.run(s3))
#-----------------------------
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.add(s1,s2)
sess = tf.Session()
print(sess.run(s3))
#----------------------------
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.multiply(s1,s2)
sess = tf.Session()
print(sess.run(s3))
#-----------------------------
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.subtract(s1,s2)
sess = tf.Session()
print(sess.run(s3))
#-----------------------------
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.divide(s1,s2)
sess = tf.Session()
print(sess.run(s3))
#----------------------------
s1 = tf.constant(2)
s2 = tf.constant(3)
s3 = tf.pow(s1,s2)
sess = tf.Session()
print(sess.run(s3))
#--------------------------
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([1,2,3,4])
s3 = tf.add(s1,s2)
sess = tf.Session()
print(sess.run(s3))
#--------------------------
matrix1 = tf.constant([[5., 3.]])
matrix2 = tf.constant([[2.],
                   [2.]])
product = tf.matmul(matrix1, matrix2)
with tf.Session() as sess:
    result = sess.run(product)
    print (result)
#----------------------------
matrix2 = tf.matrix_transpose(matrix1)
with tf.Session() as sess:
    result = sess.run(matrix2)
    print (result)

b'Hi Mahmoud'
50
600
-10
0.6666666666666666
8
[ 6  8 10 12]
[[16.]]
[[5.]
 [3.]]


# Graph in TensorFlow
Graphs are used by tf.functions to represent the function's computations. Each graph contains a set of tf.Operation objects, which represent units of computation; and tf.Tensor objects, which represent the units of data that flow between operations.

In [166]:
graph=tf.get_default_graph() # Just declare it once in program .
#graph.get_operations() # Print all operation that graph holding 


# Eager Execution
if we enable Eager Execution we can do any operation without Session !

In [ ]:
tf.enable_eager_execution() # Just declare it once in program .

In [ ]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.encode_base64("hello world"))

print(tf.square(2) + tf.square(3))